name: Update Google Sheet with SEC Data

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread requests aiohttp aiofiles

      - name: Run script to update Google Sheet
        env:
          GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python -m SEC_company_tickers_exchange.py
