name: Sheet to SQL Database

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Python Dependencies
      run: |
        pip install gspread oauth2client
    
    - name: Read Google Sheet and Write to SQL Database
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
      run: |
        python Full_Database_Backend/src/update_sql.py
    
    - name: Check and Set Working Directory
      run: |
        echo "Current working directory:"
        pwd
        echo "Setting working directory to GitHub workspace..."
        cd $GITHUB_WORKSPACE
        pwd
    
    - name: Diagnose File Staging Issues
      run: |
        echo "Adding database and JSON files to staging..."
        echo "Full path of the database file:"
        readlink -f "Full_Database_Backend/src/Full_Database_Backend.db"
        echo "Full path of the JSON file:"
        readlink -f "Full_Database_Backend/src/Full_Database_Backend.json"
        echo "Attempting to force add files with absolute paths:"
        git add -f $(readlink -f "Full_Database_Backend/src/Full_Database_Backend.db")
        git add -f $(readlink -f "Full_Database_Backend/src/Full_Database_Backend.json")
        echo "Files staged for commit:"
        git status
        git commit -m "Updated database and JSON files"
        echo "Pushing to remote repository..."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
