name: Sheet to SQL Database

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Python Dependencies
      run: |
        pip install gspread oauth2client
    
    - name: Read Google Sheet and Write to SQL Database
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
      run: |
        python Full_Database_Backend/src/update_sql.py
    
    - name: Check current working directory
      run: |
        echo "Checking the current working directory..."
        pwd
        ls -l Full_Database_Backend/src/

    - name: Commit and Push Database Files
      run: |
        git config --global user.name 'DRRUTHSEX'
        git config --global user.email 'drsf500@gmail.com'
        echo "Adding database and JSON files to staging..."
        echo "Full path of the database file:"
        if [ -f "Full_Database_Backend/src/Full_Database_Backend.db" ]; then
          readlink -f "Full_Database_Backend/src/Full_Database_Backend.db"
          git add Full_Database_Backend/src/Full_Database_Backend.db --verbose
        else
          echo "Database file not found!"
        fi
        echo "Full path of the JSON file:"
        if [ -f "Full_Database_Backend/src/Full_Database_Backend.json" ]; then
          readlink -f "Full_Database_Backend/src/Full_Database_Backend.json"
          git add Full_Database_Backend/src/Full_Database_Backend.json --verbose
        else
          echo "JSON file not found!"
        fi
        echo "Files staged for commit:"
        git status
        git commit -m "Updated database and JSON files"
        echo "Pushing to remote repository..."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
